const {test}=require('node:test'),assert=require('node:assert/strict');
const {measureContext,markdownSections,maxBytes}=require('../src/context-meter.cjs');
const {ContextMeterRunner}=require('../src/context-meter-runner.cjs');

test('real encoding counts match independent OpenAI tiktoken reference examples',()=>{
  // Fixed counts from https://developers.openai.com/cookbook/examples/how_to_count_tokens_with_tiktoken
  // Section 5, comparing encodings; checked 2026-09-12. These expectations are not generated by this package.
  for(const [text,cl100k_base,o200k_base]of [['antidisestablishmentarianism',6,6],['2 + 2 = 4',7,7],['お誕生日おめでとう',9,8]]){
    for(const [tokenizer,expected]of Object.entries({cl100k_base,o200k_base})){const result=measureContext({text,tokenizer});assert.equal(result.total,expected);assert.equal(result.approximate,false);assert.equal(result.tokenizer,tokenizer);assert.equal(result.sections[0].tokens,expected);}
  }
  assert.equal(measureContext({text:''}).total,0);
});
test('literal special markers are ordinary text and heuristics are explicitly labelled',()=>{
  for(const tokenizer of ['o200k_base','cl100k_base']){const result=measureContext({text:'<|endoftext|>',tokenizer});assert.equal(result.total,7);assert.match(result.note,/ordinary text/);}
  const heuristic=measureContext({text:'😀abcé',tokenizer:'chars4'});assert.equal(heuristic.total,2);assert.equal(heuristic.approximate,true);assert.match(heuristic.note,/not an exact Claude/);assert.equal(heuristic.bytes,9);
});
test('heading subtrees include children, stop at peers and retain preamble and exact offsets',()=>{
  const text='intro\r\n# One\r\nbody\r\n## Child\r\nchild\r\n# Two\r\nend';
  const result=measureContext({text,tokenizer:'cl100k_base'}),[preamble,one,child,two]=result.sections;
  assert.deepEqual(result.sections.map(({title,level,line})=>({title,level,line})),[{title:'Preamble',level:0,line:1},{title:'One',level:1,line:2},{title:'Child',level:2,line:4},{title:'Two',level:1,line:6}]);
  assert.equal(text.slice(preamble.from,preamble.to),'intro\r\n');assert.equal(one.to,two.from);assert.equal(child.to,two.from);assert.equal(two.to,text.length);assert.equal(result.lines,7);assert.equal(result.sectionsOverlap,true);
  for(const section of result.sections)assert.equal(section.tokens,measureContext({text:text.slice(section.from,section.to),tokenizer:'cl100k_base'}).total);
  assert.ok(one.tokens>child.tokens);
});
test('setext headings, fences, frontmatter and indentation do not create false outline sections',()=>{
  const text='---\n# metadata\n---\npreamble\n\nTitle\n=====\nbody\n\n```md\n# hidden\n~~~\n```\n\n~~~\nFake\n---\n~~~\n\nSub title\ncontinued\n---\n    # indented\n# Last ###\n';
  const sections=markdownSections(text);assert.deepEqual(sections.map(section=>section.title),['Preamble','Title','Sub title continued','Last']);
  assert.equal(sections[1].from,text.indexOf('Title'));assert.equal(sections[2].from,text.indexOf('Sub title'));assert.equal(sections[2].level,2);assert.equal(sections[1].to,sections[3].from);
  assert.equal(markdownSections('# ###')[1].title,'(untitled)');assert.equal(markdownSections('\uFEFF# Start')[1].title,'Start');
  assert.equal(markdownSections('```\n# never closed').length,1);assert.equal(markdownSections('---\n# no closing frontmatter')[1].title,'no closing frontmatter');
});
test('UTF-8 byte, heading and tokenizer bounds reject inputs without partial counts',()=>{
  assert.equal(measureContext({text:'é'.repeat(maxBytes/2),tokenizer:'chars4'}).bytes,maxBytes);
  assert.throws(()=>measureContext({text:'漢'.repeat(Math.ceil(maxBytes/3))}),/1 MiB/);assert.throws(()=>measureContext({text:'\ud800'}),/Unicode/);
  assert.throws(()=>measureContext({text:'abc',tokenizer:'claude-exact'}),/Choose/);assert.throws(()=>measureContext({text:'# h\n'.repeat(1001)}),/1,000/);
  assert.equal(markdownSections('# h\n'.repeat(1000)).length,1001);
});
test('worker returns real counts, and request-specific cancellation/latest-wins prevent stale results',async()=>{
  const runner=new ContextMeterRunner();
  try{
    const first=runner.run({requestId:1,text:'antidisestablishmentarianism',tokenizer:'o200k_base'});assert.equal(runner.cancel(0),false);assert.equal(runner.cancel(1),true);assert.deepEqual(await first,{requestId:1,cancelled:true});
    const second=runner.run({requestId:2,text:'x'.repeat(maxBytes),tokenizer:'o200k_base'});const third=runner.run({requestId:3,text:'お誕生日おめでとう',tokenizer:'cl100k_base'});assert.deepEqual(await second,{requestId:2,cancelled:true});const result=await third;assert.equal(result.requestId,3);assert.equal(result.total,9);assert.equal(result.approximate,false);assert.equal(runner.job,null);
    const pending=runner.run({requestId:4,text:'x'.repeat(maxBytes)});const invalid=await runner.run({requestId:5,text:'abc',tokenizer:'unknown'});assert.match(invalid.error,/Choose/);assert.deepEqual(await pending,{requestId:4,cancelled:true});
    const failure=await runner.run({requestId:6,text:'# h\n'.repeat(1001)});assert.match(failure.error,/1,000/);assert.equal(failure.total,undefined);
  }finally{runner.close();}
});
test('timeout and close terminate work and return structured errors without partial totals',async()=>{
  const timed=new ContextMeterRunner(1);try{const result=await timed.run({requestId:1,text:'abc'});assert.match(result.error,/exceeded/);assert.equal(result.total,undefined);assert.equal(timed.job,null);}finally{timed.close();}
  const runner=new ContextMeterRunner();const pending=runner.run({requestId:2,text:'x'.repeat(maxBytes)});runner.close();assert.deepEqual(await pending,{requestId:2,cancelled:true});assert.match((await runner.run({requestId:3,text:'abc'})).error,/closed/);assert.match((await new ContextMeterRunner().run({requestId:-1,text:'abc'})).error,/request ID/);assert.match((await new ContextMeterRunner().run(null)).error,/request ID/);
});
