const {_electron:electron}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const os=require('node:os');
const path=require('node:path');
(async()=>{
  const dir=await fs.mkdtemp(path.join(os.tmpdir(),'openpad-editing-'));let app;
  const launch=async()=>{app=await electron.launch({...(process.env.OPENPAD_EXECUTABLE?{executablePath:process.env.OPENPAD_EXECUTABLE,args:[]}:{args:[path.resolve('.')]}),env:{...process.env,OPENPAD_USER_DATA:path.join(dir,'profile')}});const page=await app.firstWindow();page.setDefaultTimeout(8000);await page.waitForSelector('body[data-ready="true"]');return page;};
  const command=name=>app.evaluate(({BrowserWindow},name)=>BrowserWindow.getAllWindows()[0].webContents.send('command',name),name);
  try{
    let page=await launch();const errors=[];page.on('pageerror',e=>errors.push(e.message));let editor=page.locator('#editor .cm-content');await app.evaluate(({clipboard})=>{clipboard.writeText=text=>{global.copiedText=text;};});
    await editor.fill('one\ntwo\nthree');await editor.press('Control+Home');await command('bookmarkToggle');await page.waitForSelector('.bookmark-marker:visible');
    await editor.press('Control+End');await command('bookmarkNext');await page.waitForFunction(()=>document.querySelector('#position').textContent.includes('Ln 1, Col 1'));
    await command('bookmarkCopy');const copyDeadline=Date.now()+2000;while(await app.evaluate(()=>global.copiedText)!=='one'&&Date.now()<copyDeadline)await page.waitForTimeout(10);assert.equal(await app.evaluate(()=>global.copiedText),'one');
    await editor.press('Enter');await command('bookmarkNext');await page.waitForFunction(()=>document.querySelector('#position').textContent.includes('Ln 2, Col 1'));
    await command('columnEditor');await page.waitForSelector('#column-first');await page.locator('#column-first').fill('2');await page.locator('#column-last').fill('4');await page.locator('#column-position').fill('1');await page.locator('#column-mode').selectOption('number');await page.getByRole('button',{name:'Insert column',exact:true}).click();
    assert.equal(await editor.evaluate(el=>[...el.querySelectorAll('.cm-line')].map(line=>line.textContent).join('\n')),'\n1one\n2two\n3three');await command('undo');await page.waitForFunction(()=>document.querySelector('#editor .cm-content').textContent.includes('one')&&!document.querySelector('#editor .cm-content').textContent.includes('1one'));
    await command('new');await page.waitForFunction(()=>document.querySelectorAll('.tab').length===2);await command('macroStart');await editor.pressSequentially('abc');await command('macroStop');assert.match(await page.locator('#editing-status').innerText(),/3 steps/);
    await command('macroPlay');await page.waitForFunction(()=>document.querySelector('#editor .cm-content').textContent==='abcabc');await command('undo');await page.waitForFunction(()=>document.querySelector('#editor .cm-content').textContent==='abc');
    await command('macroSave');await page.waitForSelector('#macro-name');await page.locator('#macro-name').fill('Insert abc');await page.getByRole('button',{name:'Save macro',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('#dialog').open);
    await command('quit');await app.close();app=null;
    page=await launch();editor=page.locator('#editor .cm-content');await command('macroLoad');await page.waitForSelector('#picker-query');await page.locator('#picker-query').fill('Insert abc');await page.locator('#picker-query').press('Enter');await command('macroPlay');await page.waitForFunction(()=>document.querySelector('#editor .cm-content').textContent==='abcabc');
    await page.locator('#tabs button').filter({hasText:/Untitled-1/}).first().click();assert.ok(await page.locator('#editor .bookmarks .bookmark-marker:visible').count()>0);
    const file=path.join(dir,'tail.txt');await fs.writeFile(file,'initial\n');await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},file);await command('open');await page.waitForFunction(()=>document.querySelector('#filepath').textContent.endsWith('tail.txt'));
    await editor.press('Control+Home');await command('bookmarkToggle');await command('split');await page.waitForSelector('.split-panel select');const fileId=await page.locator('.split-panel select').first().locator('option').filter({hasText:'tail.txt'}).getAttribute('value');await page.locator('.split-panel select').first().selectOption(fileId);
    await command('monitor');await page.locator('.split-panel .cm-content').first().pressSequentially('BLOCKED');assert.doesNotMatch(await editor.innerText(),/BLOCKED/);
    await fs.appendFile(file,'appended\n');await page.waitForFunction(()=>document.querySelector('#editor .cm-content').textContent.includes('appended'));await command('bookmarkNext');await page.waitForFunction(()=>document.querySelector('#position').textContent.includes('Ln 1, Col 1'));await command('split');
    await editor.click();await editor.pressSequentially('SHOULD NOT INSERT');assert.doesNotMatch(await editor.innerText(),/SHOULD/);assert.match(await page.locator('#status').innerText(),/All changes saved/);
    await command('monitor');await editor.pressSequentially('edit');assert.match(await page.locator('#status').innerText(),/Unsaved/);assert.equal(await fs.readFile(file,'utf8'),'initial\nappended\n');assert.deepEqual(errors,[]);
    await command('save');await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('All changes saved'));await command('monitor');await fs.writeFile(file,Buffer.from([255]));await page.waitForFunction(()=>document.querySelector('#editing-status').textContent.startsWith('Monitoring stopped:'));await editor.pressSequentially('writable');assert.match(await editor.innerText(),/writable/);
    const columns='\ta\nb\ne\u0301z';await editor.fill(columns);await editor.press('Control+Home');await command('columnEditor');await page.waitForSelector('#column-units');assert.equal(await page.locator('#column-units').inputValue(),'tabs');await page.locator('#column-first').fill('1');await page.locator('#column-last').fill('3');await page.locator('#column-position').fill('3');await page.locator('#column-text').fill('X');await page.getByRole('button',{name:'Insert column',exact:true}).click();assert.equal((await editor.locator('.cm-line').allTextContents()).join('\n'),'  X  a\nb X\ne\u0301zX');await command('undo');await page.waitForFunction(text=>[...document.querySelectorAll('#editor .cm-line')].map(line=>line.textContent).join('\n')===text,columns);
    await editor.press('Control+Home');await command('columnEditor');await page.waitForSelector('#column-units');await page.locator('#column-units').selectOption('characters');await page.locator('#column-first').fill('1');await page.locator('#column-last').fill('1');await page.locator('#column-position').fill('2');await page.locator('#column-text').fill('Y');await page.getByRole('button',{name:'Insert column',exact:true}).click();assert.equal((await editor.locator('.cm-line').allTextContents()).join('\n'),'\tYa\nb\ne\u0301z');
    await editor.fill('abc');await editor.press('Control+Home');await command('macroStart');await editor.press('Delete');await command('macroStop');await page.waitForFunction(()=>document.querySelector('#editing-status').textContent==='Macro: 1 steps');await command('macroRepeat');await page.waitForSelector('#macro-mode');await page.locator('#macro-mode').selectOption('end');await page.getByRole('button',{name:'Run macro',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('#dialog').open&&document.querySelector('#editor .cm-content').cmTile.root.view.state.doc.length===0);assert.equal(await page.locator('#editing-status').textContent(),'Macro: 2 repetitions');await command('undo');await page.waitForFunction(()=>document.querySelector('#editor .cm-content').cmTile.root.view.state.doc.toString()==='bc');
    console.log('PASS: bookmarks/navigation/copy/edit tracking/restoration; numbered and tab-stop/Unicode columns with undo; macro recording/playback/undo/persistence; read-only file monitoring and return to editing.');
  }finally{if(app){app.process().kill();await app.close().catch(()=>{});}await fs.rm(dir,{recursive:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
