const {_electron:electron} = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const os = require('node:os');
const path = require('node:path');
(async () => {
  const dir = await fs.mkdtemp(path.join(os.tmpdir(),'openpad-features-'));
  let app;
  const errors=[];
  const launch = async () => {
    app = await electron.launch({...(process.env.OPENPAD_EXECUTABLE ? {executablePath:process.env.OPENPAD_EXECUTABLE,args:[]} : {args:[path.resolve('.')]}),env:{...process.env,OPENPAD_USER_DATA:path.join(dir,'profile')}});
    const page=await app.firstWindow(); page.setDefaultTimeout(8000); page.on('pageerror',error=>errors.push(error.message)); await page.waitForSelector('body[data-ready="true"]');
    await app.evaluate(({dialog})=>{ global.testDialogErrors=[]; dialog.showMessageBox=async (...args)=>{const options=args.at(-1); if(options.type==='error') global.testDialogErrors.push(options.message); return {response:2}; }; });
    return page;
  };
  const command = name => { console.log(`Checking ${name}`); return app.evaluate(({BrowserWindow},name)=>BrowserWindow.getAllWindows()[0].webContents.send('command',name),name); };
  try {
    let page=await launch();
    let editor=page.locator('#editor .cm-content');
    await editor.fill('# Recovery\n\n- first\n- second\n<script>window.injected = true</script>');
    await command('markdown'); await page.waitForSelector('#markdown-preview h1');
    assert.equal(await page.locator('#markdown-preview h1').innerText(),'Recovery');
    assert.equal(await page.locator('#markdown-preview script').count(),0);
    assert.equal(await page.evaluate(()=>window.injected),undefined);
    await command('settings'); await page.waitForSelector('#setting-theme');
    await page.locator('#setting-theme').selectOption('light'); await page.locator('#setting-size').fill('17');
    await page.getByRole('button',{name:'Apply settings',exact:true}).click(); await page.waitForFunction(()=>!document.querySelector('#dialog').open);
    assert.equal(await page.locator('html').getAttribute('data-theme'),'light');
    await command('shortcuts');await page.waitForSelector('#shortcut-filter');
    await page.getByRole('textbox',{name:'New',exact:true}).fill('Ctrl+Alt+N');
    await page.getByRole('button',{name:'Apply shortcuts',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('#dialog').open);
    assert.equal(await app.evaluate(({Menu})=>Menu.getApplicationMenu().getMenuItemById('new').accelerator),'Ctrl+Alt+N');
    await command('replacePreview'); await page.waitForSelector('#preview-find');
    await page.locator('#preview-find').fill('first\n- second'); await page.locator('#preview-replace').fill('replaced');
    await page.getByRole('button',{name:'Preview',exact:true}).last().click();
    assert.match(await page.locator('#replacement-count').innerText(),/^1 replacements/);
    assert.match(await editor.innerText(),/first/);
    await page.getByRole('button',{name:'Apply replacement',exact:true}).click();
    assert.match(await editor.innerText(),/replaced/);
    await command('undo'); await page.waitForFunction(()=>document.querySelector('#editor .cm-content').textContent.includes('first'));
    await command('pin'); await page.waitForSelector('.pinned-tabs .tab');
    await command('group'); await page.waitForSelector('#group-name'); await page.locator('#group-name').fill('Research'); await page.getByRole('button',{name:'Apply',exact:true}).click();
    await command('new'); await page.waitForFunction(()=>document.querySelectorAll('.tab').length===2); await editor.fill('second buffer');
    await command('compare'); await page.waitForSelector('.cm-mergeView'); assert.equal(await page.locator('.cm-mergeView [contenteditable="true"]').count(),0); await page.locator('#dialog-close').click();
    await command('split'); await page.waitForSelector('.split-panel .cm-content');
    await page.locator('.split-panel .cm-content').first().fill('shared edit');
    const selected=await page.locator('.split-panel select').first().inputValue();
    await page.locator('.split-panel select').nth(1).selectOption(selected);
    await page.waitForFunction(()=>document.querySelectorAll('.split-panel .cm-content')[1].textContent==='shared edit');
    await command('split');
    await command('saveWorkspace'); await page.waitForSelector('#workspace-name'); await page.locator('#workspace-name').fill('Test workspace'); await page.getByRole('button',{name:'Save workspace',exact:true}).click(); await page.waitForFunction(()=>!document.querySelector('#dialog').open);
    await command('palette'); await page.waitForSelector('#picker-query'); await page.locator('#picker-query').fill('quick open'); await page.locator('#picker-query').press('Enter'); await page.waitForFunction(()=>document.querySelector('#dialog-title').textContent.startsWith('Quick open')); await page.locator('#dialog-close').click();
    const folder=path.join(dir,'files'); await fs.mkdir(folder); await fs.writeFile(path.join(folder,'needle.txt'),'target line\nother');
    await app.evaluate(({dialog},folder)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[folder]});},folder);
    await command('folder'); await page.waitForSelector('#picker-query'); await page.locator('#dialog-close').click();
    await command('folderSearch'); await page.locator('#folder-query').fill('target'); await page.locator('#folder-start').click(); await page.waitForFunction(()=>document.querySelector('#folder-progress').textContent.startsWith('Finished'));
    assert.equal(await page.locator('#folder-results button').count(),1);
    await page.locator('#folder-results button').click(); await page.waitForFunction(()=>document.querySelector('#filepath').textContent.endsWith('needle.txt'));
    await editor.fill('unsaved after opening');
    await page.locator('#search-scope').selectOption('tabs');await page.locator('#folder-query').fill('unsaved after opening');await page.locator('#folder-start').click();await page.waitForFunction(()=>document.querySelector('#folder-progress').textContent.startsWith('Finished')&&document.querySelector('#folder-progress').textContent.includes('Open buffers'));
    assert.equal(await page.locator('#folder-results button').count(),1);
    await fs.writeFile(path.join(folder,'slow.txt'),'a'.repeat(100000)+'!');
    await page.locator('#search-scope').selectOption('folder');await page.locator('#folder-regex').check();await page.locator('#folder-query').fill('(a+)+$');await page.locator('#folder-start').click();await page.waitForTimeout(200);await page.locator('#folder-cancel').click();await page.waitForFunction(()=>document.querySelector('#folder-progress').textContent.startsWith('Cancelled'));
    await page.waitForTimeout(1000);
    const snapshot=JSON.parse(JSON.parse(await fs.readFile(path.join(dir,'profile','session.json'),'utf8')).payload);
    assert.ok(snapshot.docs.some(doc=>doc.text==='unsaved after opening'));
    assert.deepEqual(await app.evaluate(()=>global.testDialogErrors),[]);
    app.process().kill(); await app.close().catch(()=>{}); app=null;
    page=await launch(); editor=page.locator('#editor .cm-content');
    assert.equal(await editor.innerText(),'unsaved after opening');
    assert.match(await page.locator('#status').innerText(),/Unsaved/);
    assert.equal(await page.locator('html').getAttribute('data-theme'),'light');
    assert.equal(await app.evaluate(({Menu})=>Menu.getApplicationMenu().getMenuItemById('new').accelerator),'Ctrl+Alt+N');
    assert.equal(await page.locator('.pinned-tabs .tab').count(),1);
    assert.equal(await page.locator('#documents summary').innerText(),'Research');
    await command('loadWorkspace'); await page.waitForSelector('#picker-query'); await page.locator('#picker-query').fill('Test workspace'); await page.locator('#picker-query').press('Enter'); await page.waitForFunction(()=>document.querySelectorAll('.tab').length===2);
    await fs.mkdir('test-artifacts',{recursive:true}); await page.screenshot({path:'test-artifacts/features.png'});
    assert.deepEqual(errors,[]);
    console.log('PASS: sanitized Markdown, settings, multiline replacement preview/undo, pinned/grouped tabs, read-only compare, shared split panes, named workspace, palette, folder search, recovery after process close.');
  } finally { if(app) { app.process().kill(); await app.close().catch(()=>{}); } await fs.rm(dir,{recursive:true}); }
})().catch(error=>{console.error(error);process.exitCode=1;});
