const {_electron:electron}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
(async()=>{
  const root=await fs.mkdtemp(path.join(os.tmpdir(),'openpad-marks-'));let app;
  const launch=()=>electron.launch({...(process.env.OPENPAD_EXECUTABLE?{executablePath:process.env.OPENPAD_EXECUTABLE,args:[]}:{args:[path.resolve('.')]}),env:{...process.env,OPENPAD_USER_DATA:root}});
  try{
    app=await launch();let page=await app.firstWindow();page.setDefaultTimeout(8000);await page.waitForSelector('body[data-ready="true"]');
    const command=name=>app.evaluate(({BrowserWindow},name)=>BrowserWindow.getAllWindows()[0].webContents.send('command',name),name);
    let editor=page.locator('#editor .cm-content');await editor.fill('alpha beta alpha');await editor.press('Control+Home');for(let i=0;i<5;i++)await editor.press('Shift+ArrowRight');
    await command('markText');await page.locator('#mark-color').selectOption('2');await page.getByRole('button',{name:'Mark all exact matches',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('#editor .openpad-mark-2').length===2);
    await command('markNext');assert.equal(await page.evaluate(()=>window.getSelection().toString()),'alpha');
    await app.evaluate(({clipboard})=>{clipboard.writeText=text=>global.__markCopy=text;});await command('markCopy');await page.waitForTimeout(80);assert.equal(await app.evaluate(()=>global.__markCopy),'alpha\nalpha');
    await editor.press('Control+Home');await editor.press('!');await page.waitForFunction(()=>document.querySelector('#editor .cm-line').textContent.startsWith('!'));
    assert.equal(await page.locator('#editor .openpad-mark-2').count(),2);const exited=new Promise(resolve=>app.process().once('exit',resolve));await command('quit');await exited;await app.close().catch(()=>{});app=null;
    app=await launch();page=await app.firstWindow();await page.waitForSelector('body[data-ready="true"]');await page.waitForFunction(()=>document.querySelectorAll('#editor .openpad-mark-2').length===2);assert.ok((await page.locator('#editor .cm-content').textContent()).startsWith('!'));
    await app.evaluate(({clipboard})=>{clipboard.writeText=text=>global.__markCopy=text;});await command('markCopy');await page.waitForTimeout(80);assert.equal(await app.evaluate(()=>global.__markCopy),'alpha\nalpha');
    await command('markText');await page.locator('#mark-color').selectOption('3');await page.locator('#dialog-close').click();await command('markCopy');await page.waitForTimeout(80);assert.equal(await app.evaluate(()=>global.__markCopy),'');
    await command('markClear');await page.waitForFunction(()=>!document.querySelector('#editor .openpad-mark'));
    editor=page.locator('#editor .cm-content');await editor.fill('α1\nB22\nkeep');await command('markText');await page.locator('#mark-color').selectOption('4');await page.locator('#mark-query').fill('[αB]\\d+');await page.locator('#mark-regex').check();await page.getByRole('button',{name:'Mark expression matches',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('#dialog').open);assert.deepEqual(await page.locator('#editor .openpad-mark-4').allTextContents(),['α1','B22']);
    await editor.fill('a'.repeat(100000)+'!');await command('markText');await page.locator('#mark-query').fill('(a+)+$');await page.locator('#mark-regex').check();await page.getByRole('button',{name:'Mark expression matches',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#mark-status').textContent==='Matching…');await page.getByRole('button',{name:'Cancel matching',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#mark-status').textContent==='Cancelled');assert.equal(await page.locator('#editor .openpad-mark').count(),0);await page.getByRole('button',{name:'Mark expression matches',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#mark-status').textContent==='Matching…');await page.locator('#mark-query').fill('!$');await page.waitForFunction(()=>document.querySelector('#mark-status').textContent==='Cancelled');await page.getByRole('button',{name:'Mark expression matches',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('#dialog').open);await editor.press('Control+End');await page.waitForSelector('#editor .openpad-mark-4');assert.equal(await page.locator('#editor .openpad-mark-4').textContent(),'!');
    console.log('PASS: regex Unicode matches/cancellation/restart and exact colored matches, navigation/copy, edit mapping, recovery and clearing.');
  }finally{if(app){app.process().kill();await app.close().catch(()=>{});}await fs.rm(root,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
