const {_electron:electron}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const path=require('node:path');
const os=require('node:os');
(async()=>{
  const root=await fs.mkdtemp(path.join(os.tmpdir(),'openpad-transform-'));let app;
  try{
    app=await electron.launch({...(process.env.OPENPAD_EXECUTABLE?{executablePath:process.env.OPENPAD_EXECUTABLE,args:[]}:{args:[path.resolve('.')]}),env:{...process.env,OPENPAD_USER_DATA:root}});
    const page=await app.firstWindow();page.setDefaultTimeout(8000);await page.waitForSelector('body[data-ready="true"]');
    const command=name=>app.evaluate(({BrowserWindow},name)=>BrowserWindow.getAllWindows()[0].webContents.send('command',name),name);
    const editor=page.locator('#editor .cm-content');await editor.fill('first\nélan\nlast');await editor.press('Control+Home');await editor.press('ArrowDown');await editor.press('Home');await editor.press('Shift+End');await command('uppercase');await page.waitForFunction(()=>document.querySelector('#editor .cm-content').textContent.includes('ÉLAN'));assert.equal((await editor.locator('.cm-line').allTextContents()).join('\n'),'first\nÉLAN\nlast');
    await command('undo');await page.waitForFunction(()=>document.querySelector('#editor .cm-content').textContent.includes('élan'));
    await editor.fill('10\n2\n1');await editor.press('Control+Home');await command('transform');await page.waitForSelector('#transform-operation');await page.locator('#transform-operation').selectOption('numeric');await page.getByRole('button',{name:'Preview transformation',exact:true}).click();await page.waitForSelector('.cm-mergeView');assert.equal((await editor.locator('.cm-line').allTextContents()).join('\n'),'10\n2\n1');await page.getByRole('button',{name:'Apply transformation',exact:true}).click();assert.equal((await editor.locator('.cm-line').allTextContents()).join('\n'),'1\n2\n10');await command('undo');await page.waitForFunction(()=>document.querySelector('#editor .cm-content').textContent==='1021');
    await editor.fill('élan\nrose\nkeep');await editor.press('Control+Home');await command('addCursorBelow');await editor.press('Shift+End');await command('uppercase');await page.waitForFunction(()=>document.querySelector('#editor .cm-content').cmTile.root.view.state.doc.toString()==='ÉLAN\nROSE\nkeep');await command('undo');await page.waitForFunction(()=>document.querySelector('#editor .cm-content').cmTile.root.view.state.doc.toString()==='élan\nrose\nkeep');await command('transform');await page.waitForSelector('#transform-operation');await page.locator('#transform-operation').selectOption('upper');await page.getByRole('button',{name:'Preview transformation',exact:true}).click();await page.waitForSelector('.cm-mergeView');await page.getByRole('button',{name:'Apply transformation',exact:true}).click();assert.equal((await editor.locator('.cm-line').allTextContents()).join('\n'),'ÉLAN\nROSE\nkeep');await command('undo');await page.waitForFunction(()=>document.querySelector('#editor .cm-content').cmTile.root.view.state.doc.toString()==='élan\nrose\nkeep');await command('simplifySelection');
    await editor.fill('a\n \nb');await editor.press('Control+Home');await editor.press('ArrowDown');await editor.press('Home');await editor.press('Shift+End');await command('removeBlank');await page.waitForFunction(()=>document.querySelector('#editor .cm-content').cmTile.root.view.state.doc.toString()==='a\nb');await command('undo');await page.waitForFunction(()=>document.querySelector('#editor .cm-content').cmTile.root.view.state.doc.toString()==='a\n \nb');
    await editor.fill('a \tb  ');await command('whitespace');await page.waitForSelector('#editor .cm-highlightSpace');assert.ok(await page.locator('#editor .cm-highlightTab').count());
    await editor.fill('function example() {\n  return 1;\n}');await page.locator('#language').selectOption('JavaScript');await page.waitForSelector('.cm-foldGutter');await page.waitForTimeout(150);await command('foldAll');await page.waitForSelector('.cm-foldPlaceholder');await command('unfoldAll');await page.waitForFunction(()=>!document.querySelector('.cm-foldPlaceholder'));
    console.log('PASS: selected Unicode transformation/undo, full-buffer numeric preview/apply/undo, whitespace marks and JavaScript folding controls.');
  }finally{if(app){app.process().kill();await app.close().catch(()=>{});}await fs.rm(root,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
