const { _electron: electron } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const os = require('node:os');
const path = require('node:path');
(async () => {
  const temp = await fs.mkdtemp(path.join(os.tmpdir(), 'openpad-ui-'));
  const options = process.env.OPENPAD_EXECUTABLE ? { executablePath: process.env.OPENPAD_EXECUTABLE, args: [] } : { args: [path.resolve(__dirname, '..')] };
  const app = await electron.launch({ ...options, env:{ ...process.env, OPENPAD_USER_DATA:path.join(temp,'profile') } });
  const errors = [];
  try {
    const page = await app.firstWindow();
    page.on('pageerror', error => errors.push(error.message));
    await page.waitForSelector('.cm-content');
    await page.waitForSelector('body[data-ready="true"]');
    const editor = page.locator('.cm-content');
    await editor.fill('const greeting = "Hello, 世界";');
    await page.waitForFunction(() => document.querySelector('#status').textContent.includes('Unsaved'));
    const target = path.join(temp, 'hello.js');
    await app.evaluate(({ dialog }, target) => { dialog.showSaveDialog = async () => ({ canceled: false, filePath: target }); }, target);
    await page.locator('[data-command="save"]').click();
    await page.waitForFunction(() => document.querySelector('#filepath').textContent.endsWith('hello.js'));
    assert.equal(await fs.readFile(target, 'utf8'), 'const greeting = "Hello, 世界";');
    assert.equal(await page.locator('#language').inputValue(), 'JavaScript');
    await page.locator('header [data-command="new"]').click();
    await editor.fill('second document');
    await page.locator('#tabs button').filter({ hasText: /^hello.js$/ }).click();
    assert.equal(await editor.innerText(), 'const greeting = "Hello, 世界";');
    await page.locator('[data-command="find"]').click();
    assert.equal(await page.locator('.cm-search').count(), 1);
    await page.locator('.cm-search input[name="search"]').fill('Hello');
    await page.locator('.cm-search input[name="replace"]').fill('Welcome');
    await page.locator('.cm-search button[name="replaceAll"]').click();
    assert.equal(await editor.innerText(), 'const greeting = "Welcome, 世界";');
    await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].webContents.send('command', 'undo'));
    await page.waitForFunction(() => document.querySelector('.cm-content').textContent.includes('Hello'));
    await page.locator('#wrap').click();
    assert.equal(await page.locator('#wrap').getAttribute('aria-pressed'), 'true');
    await app.evaluate(({ dialog }) => { dialog.showMessageBox = async () => ({ response: 2 }); });
    await page.locator('#tabs button').filter({ hasText: /Untitled-2/ }).click();
    await page.getByRole('button', { name: 'Close Untitled-2', exact: true }).click();
    assert.equal(await page.locator('.tab').count(), 2);
    await app.evaluate(({ dialog }) => { dialog.showMessageBox = async () => ({ response: 1 }); });
    await page.getByRole('button', { name: 'Close Untitled-2', exact: true }).click();
    await page.waitForFunction(() => document.querySelectorAll('.tab').length === 1);
    const crlf = path.join(temp, 'windows.txt');
    await fs.writeFile(crlf, '\uFEFFfirst\r\nsecond\r\n');
    await app.evaluate(({ dialog }, file) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [file] }); }, crlf);
    await page.locator('[data-command="open"]').click();
    await page.waitForFunction(() => document.querySelector('#filepath').textContent.endsWith('windows.txt'));
    assert.equal(await page.locator('#encoding').innerText(), 'UTF-8 BOM · CRLF');
    await editor.fill('changed\nsecond\n');
    await page.locator('[data-command="save"]').click();
    await page.waitForFunction(() => document.querySelector('#status').textContent.includes('All changes saved'));
    assert.deepEqual(await fs.readFile(crlf), Buffer.from('\uFEFFchanged\r\nsecond\r\n'));
    await page.locator('[data-command="open"]').click();
    assert.equal(await page.locator('.tab').count(), 2);
    await fs.mkdir(path.resolve('test-artifacts'), { recursive: true });
    await page.screenshot({ path: 'test-artifacts/editor.png' });
    assert.deepEqual(errors, []);
    console.log('PASS: edit, save, language detection, tab state, find/replace, undo, wrap, close cancel/discard, open, BOM/CRLF, duplicate open; no renderer errors.');
  } finally { await app.close(); await fs.rm(temp, { recursive: true }); }
})().catch(error => { console.error(error); process.exitCode = 1; });
