const {_electron:electron}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
(async()=>{
  const root=await fs.mkdtemp(path.join(os.tmpdir(),'openpad-utilities-'));let app;
  try{
    app=await electron.launch({...(process.env.OPENPAD_EXECUTABLE?{executablePath:process.env.OPENPAD_EXECUTABLE,args:[]}:{args:[path.resolve('.')]}),env:{...process.env,OPENPAD_USER_DATA:root}});
    const page=await app.firstWindow();page.setDefaultTimeout(8000);await page.waitForSelector('body[data-ready="true"]');
    const command=name=>app.evaluate(({BrowserWindow},name)=>BrowserWindow.getAllWindows()[0].webContents.send('command',name),name),editor=page.locator('#editor .cm-content');
    await editor.fill('abc');await editor.press('Control+End');await command('characterPanel');await page.locator('#character-code').fill('U+1F600');await page.getByRole('button',{name:'Insert character',exact:true}).click();assert.equal(await editor.textContent(),'abc😀');await command('undo');await page.waitForFunction(()=>document.querySelector('#editor .cm-content').textContent==='abc');
    await command('checksum');await page.waitForFunction(()=>document.querySelector('#checksum-status').textContent==='3 UTF-8 bytes');const values=await page.locator('#checksum-values code').allTextContents();assert.equal(values[0],'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad');assert.equal(values[1],'ddaf35a193617abacc417349ae20413112e6fa4e89a97ea20a9eeee64b55d39a2192992a274fc1a836ba3c23a3feebbd454d4423643ce80e2a9ac94fa54ca49f');
    assert.equal(values[2],'900150983cd24fb0d6963f7d28e17f72');
    await app.evaluate(({clipboard})=>{clipboard.writeText=text=>global.__checksum=text;});await page.getByRole('button',{name:'Copy SHA-256',exact:true}).click();await page.waitForTimeout(50);assert.equal(await app.evaluate(()=>global.__checksum),values[0]);await page.locator('#dialog-close').click();assert.equal(await editor.textContent(),'abc');
    const encoded=path.join(root,'encoded.txt');await fs.writeFile(encoded,Buffer.from('fffe61000d000a00','hex'));await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},encoded);await command('open');await page.waitForFunction(()=>document.querySelector('#filepath').textContent.endsWith('encoded.txt'));await editor.press('Control+End');await editor.pressSequentially('unsaved');await command('fileChecksum');await page.waitForFunction(()=>document.querySelector('#file-checksum-status').textContent==='8 file bytes');const fileValues=await page.locator('#file-checksum-values code').allTextContents();assert.equal(fileValues[0],'44f45785c4b9aa4bfe48cce74597051829645f3f13f3f4496c6300549342b636');assert.equal(fileValues[2],'1cf77f2fdfad9260e8e182f4091e14e8');await page.getByRole('button',{name:'Copy MD5',exact:true}).click();const copyDeadline=Date.now()+2000;while(await app.evaluate(()=>global.__checksum)!=='1cf77f2fdfad9260e8e182f4091e14e8'&&Date.now()<copyDeadline)await page.waitForTimeout(10);assert.equal(await app.evaluate(()=>global.__checksum),'1cf77f2fdfad9260e8e182f4091e14e8');await page.locator('#dialog-close').click();assert.ok((await editor.textContent()).includes('unsaved'));assert.equal((await fs.readFile(encoded)).toString('hex'),'fffe61000d000a00');
    await editor.fill('😀');await editor.press('Control+Home');await command('characterPanel');assert.match(await page.locator('#character-table').textContent(),/U\+1F600/);assert.match(await page.locator('#character-table').textContent(),/f0 9f 98 80/);
    console.log('PASS: Unicode scalar insertion/undo/inspection and independent SHA-256/SHA-512 known-answer checksums/copy.');
  }finally{if(app){app.process().kill();await app.close().catch(()=>{});}await fs.rm(root,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
