const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('desktop', {
  contextCorpus: request => ipcRenderer.invoke('context-corpus',request),
  mcpStart: () => ipcRenderer.invoke('mcp-start'),
  mcpStop: () => ipcRenderer.invoke('mcp-stop'),
  mcpState: () => ipcRenderer.invoke('mcp-state'),
  onMcpState: callback => ipcRenderer.on('mcp-state',(_event,value)=>callback(value)),
  onMcpRequest: callback => ipcRenderer.on('mcp-request',(_event,value)=>callback(value)),
  onMcpCancel: callback => ipcRenderer.on('mcp-cancel',(_event,value)=>callback(value)),
  mcpReply: value => ipcRenderer.send('mcp-reply',value),
  contextLint: request => ipcRenderer.invoke('context-lint',request),
  cancelContextLint: id => ipcRenderer.invoke('context-lint-cancel',id),
  contextReviewList: () => ipcRenderer.invoke('context-review-list'),
  contextReviewGet: key => ipcRenderer.invoke('context-review-get',key),
  contextReviewDecide: request => ipcRenderer.invoke('context-review-decide',request),
  cancelContextCorpus: id => ipcRenderer.invoke('context-corpus-cancel',id),
  contextCorpusOpen: request => ipcRenderer.invoke('context-corpus-open',request),
  onContextCorpusProgress: callback => ipcRenderer.on('context-corpus-progress',(_event,message)=>callback(message)),
  contextObservation: request => ipcRenderer.invoke('context-observation',request),
  exportContextHistory: id => ipcRenderer.invoke('context-history-export',id),
  contextHistory: () => ipcRenderer.invoke('context-history'),
  contextMeter: request => ipcRenderer.invoke('context-meter',request),
  cancelContextMeter: id => ipcRenderer.invoke('context-meter-cancel',id),
  contextWatchStart: options => ipcRenderer.invoke('context-watch-start',options),
  contextWatchStop: () => ipcRenderer.invoke('context-watch-stop'),
  contextWatchState: () => ipcRenderer.invoke('context-watch-state'),
  contextWatchSession: () => ipcRenderer.invoke('context-watch-session'),
  contextWatchOpen: id => ipcRenderer.invoke('context-watch-open',id),
  contextWatchCanFollow: id => ipcRenderer.invoke('context-watch-can-follow',id),
  onContextWatch: callback => ipcRenderer.on('context-watch-event',(_event,message)=>callback(message)),
  bootstrap: () => ipcRenderer.invoke('bootstrap'),
  copyText: text => ipcRenderer.invoke('copy-text',text),
  monitorRead: id => ipcRenderer.invoke('monitor-read',id),
  monitorAccept: id => ipcRenderer.invoke('monitor-accept',id),
  takeOpenFiles: () => ipcRenderer.invoke('take-open-files'),
  shortcuts: () => ipcRenderer.invoke('shortcuts'),
  setShortcuts: values => ipcRenderer.invoke('set-shortcuts',values),
  saveWorkspace: name => ipcRenderer.invoke('workspace-save', name),
  listWorkspaces: () => ipcRenderer.invoke('workspace-list'),
  loadWorkspace: name => ipcRenderer.invoke('workspace-load', name),
  snapshot: state => ipcRenderer.invoke('snapshot', state),
  openPath: (path,options) => ipcRenderer.invoke('open-path', path,options),
  refreshFolder: () => ipcRenderer.invoke('refresh-folder'),
  openFolder: () => ipcRenderer.invoke('open-folder'),
  previewSearch: request => ipcRenderer.invoke('preview-search',request),
  cancelPreviewSearch: id => ipcRenderer.invoke('preview-search-cancel',id),
  onPreviewSearchProgress: callback => ipcRenderer.on('preview-search-progress',(_event,result)=>callback(result)),
  previewPage: request => ipcRenderer.invoke('preview-page',request),
  largePreview: () => ipcRenderer.invoke('large-preview'),
  reload: doc => ipcRenderer.invoke('reload', doc),
  confirmReload: () => ipcRenderer.invoke('confirm-reload'),
  diskState: id => ipcRenderer.invoke('disk-state', id),
  textMd5: text => ipcRenderer.invoke('text-md5',text),
  fileChecksums: id => ipcRenderer.invoke('file-checksums',id),
  markMatches: request => ipcRenderer.invoke('mark-matches',request),
  cancelMarks: id => ipcRenderer.invoke('cancel-marks',id),
  search: options => ipcRenderer.invoke('search', options),
  cancelSearch: options => ipcRenderer.invoke('cancel-search',options),
  replacementPreview: request => ipcRenderer.invoke('replacement-preview',request),
  replacementCancel: () => ipcRenderer.invoke('replacement-cancel'),
  replacementApply: request => ipcRenderer.invoke('replacement-apply',request),
  onSearchResult: callback => ipcRenderer.on('search-result', (_event, result) => callback(result)),
  open: encoding => ipcRenderer.invoke('open',encoding),
  save: doc => ipcRenderer.invoke('save', doc),
  saveCopy: doc => ipcRenderer.invoke('save-copy',doc),
  renameFile: doc => ipcRenderer.invoke('rename-file',doc),
  trashFile: id => ipcRenderer.invoke('trash-file',id),
  revealFile: id => ipcRenderer.invoke('reveal-file',id),
  printDocument: doc => ipcRenderer.invoke('print-document',doc),
  importDefinition: () => ipcRenderer.invoke('import-definition'),
  exportDefinition: value => ipcRenderer.invoke('export-definition',value),
  validateCommands: values => ipcRenderer.invoke('validate-commands',values),
  runCommand: value => ipcRenderer.invoke('run-command',value),
  stopCommand: id => ipcRenderer.invoke('stop-command',id),
  onCommandResult: callback => ipcRenderer.on('command-result',(_event,message)=>callback(message)),
  confirmClose: name => ipcRenderer.invoke('confirm-close', name),
  forget: id => ipcRenderer.invoke('forget', id),
  quit: () => ipcRenderer.invoke('quit'),
  onCommand: callback => ipcRenderer.on('command', (_event, name) => callback(name))
});
